# Generated by Django 5.1.4 on 2025-02-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_uploadproduct_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('offerprice', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('productprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='uploadproduct',
        ),
    ]
