# Generated by Django 5.1.4 on 2025-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_product_addproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('offerprice', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('productprice', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='addproduct',
        ),
    ]
