# Generated by Django 5.1.4 on 2025-02-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_admin_delete_addproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('productname', models.CharField(max_length=200)),
                ('offerprice', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('productprice', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
